# Generated by Django 6.0.5 on 2026-07-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_newsletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
