# Generated by Django 6.0.5 on 2026-06-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="blog/default.jpg", upload_to="blog/images"
            ),
        ),
    ]
